[package]
name = "pallet-para-sudo-wrapper"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

inherents = { package = "sp-inherents", path = "../../../../substrate/primitives/inherents", default-features = false }
sp-std = { package = "sp-std", path = "../../../../substrate/primitives/std", default-features = false }
sp-io = { path = "../../../../substrate/primitives/io", default-features = false }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, features = ["serde"] }
sp-session = { path = "../../../../substrate/primitives/session", default-features = false }
sp-staking = { path = "../../../../substrate/primitives/staking", default-features = false, features = ["serde"] }
sp-core = { path = "../../../../substrate/primitives/core", default-features = false, features = ["serde"] }
sp-npos-elections = { path = "../../../../substrate/primitives/npos-elections", default-features = false, features = ["serde"] }

pallet-authorship = { path = "../../../../substrate/frame/authorship", default-features = false }
pallet-broker = { path = "../../../../substrate/frame/broker", default-features = false }
pallet-session = { path = "../../../../substrate/frame/session", default-features = false }
frame-support = { path = "../../../../substrate/frame/support", default-features = false }
pallet-staking = { path = "../../../../substrate/frame/staking", default-features = false }
frame-system = { path = "../../../../substrate/frame/system", default-features = false }
pallet-timestamp = { path = "../../../../substrate/frame/timestamp", default-features = false }
pallet-asset-rate = { path = "../../../../substrate/frame/asset-rate", default-features = false, optional = true }
frame-election-provider-support = { path = "../../../../substrate/frame/election-provider-support", default-features = false }

frame-benchmarking = { path = "../../../../substrate/frame/benchmarking", default-features = false, optional = true }

primitives = { package = "polkadot-primitives", path = "../../../primitives", default-features = false }
libsecp256k1 = { version = "0.7.0", default-features = false }
runtime-parachains = { package = "polkadot-runtime-parachains", path = "../../parachains", default-features = false }

xcm = { package = "staging-xcm", path = "../../../xcm", default-features = false }

[features]
default = ["std"]
no_std = []
std = [
	"frame-benchmarking?/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"inherents/std",
	"libsecp256k1/std",
	"pallet-asset-rate?/std",
	"pallet-authorship/std",
	"pallet-broker/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"parity-scale-codec/std",
	"primitives/std",
	"runtime-parachains/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-npos-elections/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"libsecp256k1/hmac",
	"libsecp256k1/static-context",
	"pallet-asset-rate/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-broker/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"primitives/runtime-benchmarks",
	"runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-asset-rate/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe?/try-runtime",
	"pallet-broker/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"runtime-parachains/try-runtime",
	"sp-runtime/try-runtime",
]
