[package]
name = "pallet-para-sudo-wrapper"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

sp-std = { package = "sp-std", path = "../../../../substrate/primitives/std", default-features = false }
sp-io = { path = "../../../../substrate/primitives/io", default-features = false }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, features = ["serde"] }
sp-session = { path = "../../../../substrate/primitives/session", default-features = false }
sp-core = { path = "../../../../substrate/primitives/core", default-features = false, features = ["serde"] }

frame-support = { path = "../../../../substrate/frame/support", default-features = false }
frame-system = { path = "../../../../substrate/frame/system", default-features = false }
frame-election-provider-support = { path = "../../../../substrate/frame/election-provider-support", default-features = false }

frame-benchmarking = { path = "../../../../substrate/frame/benchmarking", default-features = false, optional = true }

primitives = { package = "polkadot-primitives", path = "../../../primitives", default-features = false }
libsecp256k1 = { version = "0.7.0", default-features = false }

xcm = { package = "staging-xcm", path = "../../../xcm", default-features = false }

[features]
default = ["std"]
no_std = []
std = [
	"frame-benchmarking?/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"libsecp256k1/std",
	"parity-scale-codec/std",
	"primitives/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"libsecp256k1/hmac",
	"libsecp256k1/static-context",
	"primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
